FROM node:24.12.0-alpine

# Update & install required packages
RUN apk add --update bash curl

# Set work directory
WORKDIR /service

# Install dependencies
COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

# Copy app source
COPY . .

EXPOSE 2300

CMD ["yarn", "start"]
